# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b0fc174e2d34446b5b133101478810db6f8e6418dca0132a467ffeb54bad57b682f9881a9f482786b091b03133f2db2978c591aed834d98b731b1999310c2d

test:
  secret_key_base: 6563ae45574090ace99a4a6bd6335d1a1e595c9e30c0ff4af391cc7c0552fa096d8a53ad764329a6b4266360bb010c71785de47134a827169dad8c40100a2bfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
